import type { UnitDefinition } from './types';

export const AEGIS_UNIT_CATALOG: readonly UnitDefinition[] = [
  {
    id: 'ship.aegis.scout',
    name: 'Разведчик «Вектор»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'scout',
    description: 'Быстрый сенсорный корабль для разведки систем и планет.',
    assetId: 'ship.aegis.scout',
    baseCost: { metal: 420, crystal: 520, gas: 180 },
    baseSeconds: 180,
    populationCost: 1,
    hangarCost: 1,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.sensors', level: 1 }],
    stats: { speed: 14, cargo: 20, attack: 4, armor: 18, shield: 8 },
  },
  {
    id: 'ship.aegis.cargo',
    name: 'Транспорт «Магистраль»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'transport',
    description: 'Грузовой корабль для снабжения колоний и перевозки ресурсов.',
    assetId: 'ship.aegis.cargo',
    baseCost: { metal: 680, crystal: 360, gas: 240 },
    baseSeconds: 240,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.construction', level: 1 }],
    stats: { speed: 9, cargo: 1_200, attack: 2, armor: 36, shield: 12 },
  },
  {
    id: 'ship.aegis.fighter',
    name: 'Истребитель «Пика»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'fighter',
    description: 'Лёгкая ударная единица для перехвата малых кораблей.',
    assetId: 'ship.aegis.fighter',
    baseCost: { metal: 560, crystal: 440, gas: 260 },
    baseSeconds: 210,
    populationCost: 1,
    hangarCost: 1,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.weapons', level: 1 }],
    stats: { speed: 13, cargo: 30, attack: 34, armor: 22, shield: 10 },
  },
  {
    id: 'ship.aegis.frigate',
    name: 'Фрегат «Бастион»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'frigate',
    description: 'Универсальный боевой корабль с усиленным корпусом.',
    assetId: 'ship.aegis.frigate',
    baseCost: { metal: 1_400, crystal: 900, gas: 620 },
    baseSeconds: 420,
    populationCost: 3,
    hangarCost: 3,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.weapons', level: 1 },
      { technologyId: 'technology.aegis.armor', level: 1 },
    ],
    stats: { speed: 9, cargo: 120, attack: 82, armor: 110, shield: 38 },
  },
  {
    id: 'ship.aegis.colony',
    name: 'Колонизатор «Форпост»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'colonizer',
    description: 'Тяжёлый корабль с инфраструктурой основания новой колонии.',
    assetId: 'ship.aegis.colony',
    baseCost: { metal: 4_800, crystal: 3_600, gas: 2_400 },
    baseSeconds: 1_200,
    populationCost: 8,
    hangarCost: 8,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 3 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.propulsion', level: 2 },
      { technologyId: 'technology.aegis.colonization', level: 1 },
    ],
    stats: { speed: 6, cargo: 500, attack: 0, armor: 180, shield: 70 },
  },
  {
    id: 'ship.aegis.recycler',
    name: 'Переработчик «Сборщик»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'recycler',
    description: 'Сервисный корабль для извлечения ресурсов из полей обломков.',
    assetId: 'ship.aegis.recycler',
    baseCost: { metal: 980, crystal: 620, gas: 540 },
    baseSeconds: 360,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.aegis.propulsion', level: 1 }],
    stats: { speed: 8, cargo: 800, attack: 0, armor: 60, shield: 20 },
  },
  {
    id: 'defense.aegis.gun-battery',
    name: 'Кинетическая батарея',
    factionId: 'aegis',
    kind: 'defense',
    role: 'kinetic',
    description: 'Базовая противокорабельная оборона ближнего периметра.',
    assetId: 'defense.aegis.gun-battery',
    baseCost: { metal: 420, crystal: 180, gas: 80 },
    baseSeconds: 150,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 1,
    buildingRequirements: [{ buildingId: 'building.aegis.sensor-array', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.weapons', level: 1 }],
    stats: { speed: 0, cargo: 0, attack: 38, armor: 48, shield: 0 },
  },
  {
    id: 'defense.aegis.missile-battery',
    name: 'Ракетная батарея',
    factionId: 'aegis',
    kind: 'defense',
    role: 'missile',
    description: 'Залповая установка против тяжёлых и медленных целей.',
    assetId: 'defense.aegis.missile-battery',
    baseCost: { metal: 620, crystal: 340, gas: 220 },
    baseSeconds: 210,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 2,
    buildingRequirements: [{ buildingId: 'building.aegis.sensor-array', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.aegis.weapons', level: 2 }],
    stats: { speed: 0, cargo: 0, attack: 84, armor: 42, shield: 0 },
  },
  {
    id: 'defense.aegis.shield-generator',
    name: 'Щитовой генератор',
    factionId: 'aegis',
    kind: 'defense',
    role: 'shield',
    description: 'Стационарный защитный узел, усиливающий планетарный периметр.',
    assetId: 'defense.aegis.shield-generator',
    baseCost: { metal: 520, crystal: 780, gas: 360 },
    baseSeconds: 300,
    populationCost: 2,
    hangarCost: 0,
    defenseGridCost: 3,
    buildingRequirements: [{ buildingId: 'building.aegis.sensor-array', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.energy', level: 2 },
      { technologyId: 'technology.aegis.armor', level: 1 },
    ],
    stats: { speed: 0, cargo: 0, attack: 0, armor: 40, shield: 160 },
  },
  {
    id: 'ship.aegis.corvette',
    name: 'Корвет «Рубеж»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'fighter',
    description: 'Быстрый корабль сопровождения для защиты строя от лёгких целей.',
    assetId: 'ship.aegis.fighter',
    baseCost: { metal: 920, crystal: 680, gas: 420 },
    baseSeconds: 300,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.aegis.shipyard', level: 2 },
      { buildingId: 'building.aegis.tactical-academy', level: 1 },
    ],
    researchRequirements: [
      { technologyId: 'technology.aegis.weapons', level: 2 },
      { technologyId: 'technology.aegis.sensors', level: 2 },
    ],
    stats: { speed: 12, cargo: 45, attack: 58, armor: 54, shield: 22 },
  },
  {
    id: 'ship.aegis.cruiser',
    name: 'Крейсер «Оплот»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'frigate',
    description: 'Тяжёлый линейный корабль с устойчивым щитом и ракетным вооружением.',
    assetId: 'ship.aegis.frigate',
    baseCost: { metal: 3_200, crystal: 2_200, gas: 1_500 },
    baseSeconds: 780,
    populationCost: 6,
    hangarCost: 6,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.aegis.shipyard', level: 4 },
      { buildingId: 'building.aegis.tactical-academy', level: 2 },
    ],
    researchRequirements: [
      { technologyId: 'technology.aegis.armor', level: 3 },
      { technologyId: 'technology.aegis.weapons', level: 3 },
    ],
    stats: { speed: 7, cargo: 220, attack: 174, armor: 260, shield: 96 },
  },
  {
    id: 'ship.aegis.carrier',
    name: 'Носитель «Горизонт»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'transport',
    description: 'Командно-логистическая платформа для дальних операций.',
    assetId: 'ship.aegis.cargo',
    baseCost: { metal: 4_100, crystal: 3_400, gas: 2_300 },
    baseSeconds: 960,
    populationCost: 8,
    hangarCost: 8,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.aegis.shipyard', level: 5 },
      { buildingId: 'building.aegis.orbital-depot', level: 3 },
    ],
    researchRequirements: [
      { technologyId: 'technology.aegis.logistics', level: 2 },
      { technologyId: 'technology.aegis.battle-network', level: 2 },
    ],
    stats: { speed: 7, cargo: 2_400, attack: 74, armor: 330, shield: 150 },
  },
  {
    id: 'ship.aegis.dreadnought',
    name: 'Дредноут «Цитадель»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'frigate',
    description: 'Флагманский тяжёлый корпус для прорыва укреплённых рубежей.',
    assetId: 'ship.aegis.frigate',
    baseCost: { metal: 8_600, crystal: 6_900, gas: 4_800 },
    baseSeconds: 1_800,
    populationCost: 14,
    hangarCost: 14,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.aegis.shipyard', level: 6 },
      { buildingId: 'building.aegis.tactical-academy', level: 4 },
    ],
    researchRequirements: [
      { technologyId: 'technology.aegis.weapons', level: 5 },
      { technologyId: 'technology.aegis.armor', level: 5 },
      { technologyId: 'technology.aegis.shield-harmonics', level: 3 },
    ],
    stats: { speed: 5, cargo: 500, attack: 420, armor: 720, shield: 320 },
  },
  {
    id: 'defense.aegis.point-defense',
    name: 'Сеть точечного перехвата',
    factionId: 'aegis',
    kind: 'defense',
    role: 'kinetic',
    description: 'Скорострельные узлы для подавления малых кораблей.',
    assetId: 'defense.aegis.gun-battery',
    baseCost: { metal: 760, crystal: 520, gas: 260 },
    baseSeconds: 240,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 2,
    buildingRequirements: [{ buildingId: 'building.aegis.defense-foundry', level: 1 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.sensors', level: 2 },
      { technologyId: 'technology.aegis.weapons', level: 2 },
    ],
    stats: { speed: 0, cargo: 0, attack: 72, armor: 72, shield: 12 },
  },
  {
    id: 'defense.aegis.fortress-array',
    name: 'Крепостной ракетный массив',
    factionId: 'aegis',
    kind: 'defense',
    role: 'missile',
    description: 'Тяжёлый оборонительный комплекс против крупных кораблей.',
    assetId: 'defense.aegis.missile-battery',
    baseCost: { metal: 1_800, crystal: 1_300, gas: 840 },
    baseSeconds: 540,
    populationCost: 3,
    hangarCost: 0,
    defenseGridCost: 5,
    buildingRequirements: [{ buildingId: 'building.aegis.defense-foundry', level: 3 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.battle-network', level: 2 },
      { technologyId: 'technology.aegis.shield-harmonics', level: 2 },
    ],
    stats: { speed: 0, cargo: 0, attack: 210, armor: 220, shield: 90 },
  },
] as const;
