import type { UnitDefinition, UnitKind } from './types';

export const AEGIS_UNIT_CATALOG: readonly UnitDefinition[] = [
  {
    id: 'ship.aegis.scout',
    name: 'Разведчик «Вектор»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'scout',
    description: 'Быстрый сенсорный корабль для разведки систем и планет.',
    assetId: 'ship.aegis.scout',
    baseCost: { metal: 420, crystal: 520, gas: 180 },
    baseSeconds: 180,
    populationCost: 1,
    hangarCost: 1,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.sensors', level: 1 }],
    stats: { speed: 14, cargo: 20, attack: 4, armor: 18, shield: 8 },
  },
  {
    id: 'ship.aegis.cargo',
    name: 'Транспорт «Магистраль»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'transport',
    description: 'Грузовой корабль для снабжения колоний и перевозки ресурсов.',
    assetId: 'ship.aegis.cargo',
    baseCost: { metal: 680, crystal: 360, gas: 240 },
    baseSeconds: 240,
    populationCost: 2,
    hangarCost: 2,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.construction', level: 1 }],
    stats: { speed: 9, cargo: 1_200, attack: 2, armor: 36, shield: 12 },
  },
  {
    id: 'ship.aegis.fighter',
    name: 'Истребитель «Пика»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'fighter',
    description: 'Лёгкая ударная единица для перехвата малых кораблей.',
    assetId: 'ship.aegis.fighter',
    baseCost: { metal: 560, crystal: 440, gas: 260 },
    baseSeconds: 210,
    populationCost: 1,
    hangarCost: 1,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.weapons', level: 1 }],
    stats: { speed: 13, cargo: 30, attack: 34, armor: 22, shield: 10 },
  },
  {
    id: 'ship.aegis.frigate',
    name: 'Фрегат «Бастион»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'frigate',
    description: 'Универсальный боевой корабль с усиленным корпусом.',
    assetId: 'ship.aegis.frigate',
    baseCost: { metal: 1_400, crystal: 900, gas: 620 },
    baseSeconds: 420,
    populationCost: 3,
    hangarCost: 3,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.weapons', level: 1 },
      { technologyId: 'technology.aegis.armor', level: 1 },
    ],
    stats: { speed: 9, cargo: 120, attack: 82, armor: 110, shield: 38 },
  },
  {
    id: 'ship.aegis.colony',
    name: 'Колонизатор «Форпост»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'colonizer',
    description: 'Тяжёлый корабль с инфраструктурой основания новой колонии.',
    assetId: 'ship.aegis.colony',
    baseCost: { metal: 4_800, crystal: 3_600, gas: 2_400 },
    baseSeconds: 1_200,
    populationCost: 8,
    hangarCost: 8,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 3 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.propulsion', level: 2 },
      { technologyId: 'technology.aegis.colonization', level: 1 },
    ],
    stats: { speed: 6, cargo: 500, attack: 0, armor: 180, shield: 70 },
  },
  {
    id: 'ship.aegis.recycler',
    name: 'Переработчик «Сборщик»',
    factionId: 'aegis',
    kind: 'ship',
    role: 'recycler',
    description: 'Сервисный корабль для извлечения ресурсов из полей обломков.',
    assetId: 'ship.aegis.recycler',
    baseCost: { metal: 980, crystal: 620, gas: 540 },
    baseSeconds: 360,
    populationCost: 2,
    hangarCost: 2,
    buildingRequirements: [{ buildingId: 'building.aegis.shipyard', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.aegis.propulsion', level: 1 }],
    stats: { speed: 8, cargo: 800, attack: 0, armor: 60, shield: 20 },
  },
  {
    id: 'defense.aegis.gun-battery',
    name: 'Кинетическая батарея',
    factionId: 'aegis',
    kind: 'defense',
    role: 'kinetic',
    description: 'Базовая противокорабельная оборона ближнего периметра.',
    assetId: 'defense.aegis.gun-battery',
    baseCost: { metal: 420, crystal: 180, gas: 80 },
    baseSeconds: 150,
    populationCost: 1,
    hangarCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.sensor-array', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.aegis.weapons', level: 1 }],
    stats: { speed: 0, cargo: 0, attack: 38, armor: 48, shield: 0 },
  },
  {
    id: 'defense.aegis.missile-battery',
    name: 'Ракетная батарея',
    factionId: 'aegis',
    kind: 'defense',
    role: 'missile',
    description: 'Залповая установка против тяжёлых и медленных целей.',
    assetId: 'defense.aegis.missile-battery',
    baseCost: { metal: 620, crystal: 340, gas: 220 },
    baseSeconds: 210,
    populationCost: 1,
    hangarCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.sensor-array', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.aegis.weapons', level: 2 }],
    stats: { speed: 0, cargo: 0, attack: 84, armor: 42, shield: 0 },
  },
  {
    id: 'defense.aegis.shield-generator',
    name: 'Щитовой генератор',
    factionId: 'aegis',
    kind: 'defense',
    role: 'shield',
    description: 'Стационарный защитный узел, усиливающий планетарный периметр.',
    assetId: 'defense.aegis.shield-generator',
    baseCost: { metal: 520, crystal: 780, gas: 360 },
    baseSeconds: 300,
    populationCost: 2,
    hangarCost: 0,
    buildingRequirements: [{ buildingId: 'building.aegis.sensor-array', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.aegis.energy', level: 2 },
      { technologyId: 'technology.aegis.armor', level: 1 },
    ],
    stats: { speed: 0, cargo: 0, attack: 0, armor: 40, shield: 160 },
  },
] as const;

const UNITS_BY_ID = new Map(
  AEGIS_UNIT_CATALOG.map((definition) => [definition.id, definition]),
);

export function getUnitDefinition(unitId: string): UnitDefinition | undefined {
  return UNITS_BY_ID.get(unitId);
}

export function getUnitsByKind(kind: UnitKind): readonly UnitDefinition[] {
  return AEGIS_UNIT_CATALOG.filter((definition) => definition.kind === kind);
}
