import type { BuildingDefinition } from '../planet/buildingDefinitions';
import type { ResearchDefinition } from '../research/types';
import type { UnitDefinition } from '../units/types';

export const SYNOD_BUILDING_CATALOG: readonly BuildingDefinition[] = [
  {
    id: 'building.synod.concord-nexus',
    name: 'Узел согласия',
    factionId: 'synod',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 10,
    assetId: 'building.synod.concord-nexus',
    baseCost: { metal: 280, crystal: 240, gas: 60 },
    baseBuildSeconds: 58,
    requirements: [],
    economy: {
      storageCapacity: { metal: 1_800, crystal: 2_200, gas: 1_900 },
      energyConsumption: 6,
      populationCapacity: 36,
    },
  },
  {
    id: 'building.synod.matter-weave',
    name: 'Материальная ткацкая',
    factionId: 'synod',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.synod.matter-weave',
    baseCost: { metal: 190, crystal: 100, gas: 25 },
    baseBuildSeconds: 88,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 1 }],
    economy: {
      resourceProductionPerHour: { metal: 125 },
      energyConsumption: 15,
      populationUse: 1,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.synod.prism-refinery',
    name: 'Призматический очиститель',
    factionId: 'synod',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.synod.prism-refinery',
    baseCost: { metal: 170, crystal: 175, gas: 35 },
    baseBuildSeconds: 102,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 1 }],
    economy: {
      resourceProductionPerHour: { crystal: 108 },
      energyConsumption: 18,
      populationUse: 1,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.synod.flux-well',
    name: 'Потоковый коллектор',
    factionId: 'synod',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.synod.flux-well',
    baseCost: { metal: 205, crystal: 155, gas: 90 },
    baseBuildSeconds: 132,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 1 }],
    economy: {
      resourceProductionPerHour: { gas: 66 },
      energyConsumption: 21,
      populationUse: 1,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.synod.resonant-core',
    name: 'Резонансное ядро',
    factionId: 'synod',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.synod.resonant-core',
    baseCost: { metal: 245, crystal: 205, gas: 45 },
    baseBuildSeconds: 142,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 1 }],
    economy: {
      energyProduction: 130,
      populationUse: 1,
      stabilityCapacity: 55,
    },
  },
  {
    id: 'building.synod.cognition-vault',
    name: 'Когнитивное хранилище',
    factionId: 'synod',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 15,
    assetId: 'building.synod.cognition-vault',
    baseCost: { metal: 620, crystal: 690, gas: 270 },
    baseBuildSeconds: 270,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 2 }],
    economy: {
      energyConsumption: 28,
      populationUse: 2,
      stabilityDemand: 6,
    },
  },
  {
    id: 'building.synod.lattice-yard',
    name: 'Сетевая верфь',
    factionId: 'synod',
    zoneId: 'industry',
    fieldCost: 3,
    maxLevel: 15,
    assetId: 'building.synod.lattice-yard',
    baseCost: { metal: 920, crystal: 900, gas: 440 },
    baseBuildSeconds: 450,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 2 }],
    economy: {
      energyConsumption: 42,
      populationUse: 4,
      stabilityDemand: 13,
    },
  },
  {
    id: 'building.synod.deep-array',
    name: 'Дальняя сенсорная решётка',
    factionId: 'synod',
    zoneId: 'military',
    fieldCost: 1,
    maxLevel: 15,
    assetId: 'building.synod.deep-array',
    baseCost: { metal: 430, crystal: 540, gas: 230 },
    baseBuildSeconds: 210,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 1 }],
    economy: {
      energyConsumption: 14,
      populationUse: 2,
      stabilityDemand: 8,
    },
  },
  {
    id: 'building.synod.relay-archive',
    name: 'Архив ретрансляции',
    factionId: 'synod',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 15,
    assetId: 'building.synod.relay-archive',
    baseCost: { metal: 780, crystal: 860, gas: 300 },
    baseBuildSeconds: 330,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 3 }],
    economy: {
      storageCapacity: { metal: 3_600, crystal: 4_800, gas: 3_200 },
      energyConsumption: 20,
      populationUse: 2,
      stabilityDemand: 5,
    },
  },
  {
    id: 'building.synod.concord-habitat',
    name: 'Жилой контур согласия',
    factionId: 'synod',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 12,
    assetId: 'building.synod.concord-habitat',
    baseCost: { metal: 700, crystal: 980, gas: 340 },
    baseBuildSeconds: 390,
    requirements: [{ buildingId: 'building.synod.concord-nexus', level: 3 }],
    economy: {
      populationCapacity: 84,
      energyConsumption: 16,
      stabilityCapacity: 86,
    },
  },
  {
    id: 'building.synod.precision-forum',
    name: 'Форум точного командования',
    factionId: 'synod',
    zoneId: 'military',
    fieldCost: 2,
    maxLevel: 10,
    assetId: 'building.synod.precision-forum',
    baseCost: { metal: 940, crystal: 1_380, gas: 650 },
    baseBuildSeconds: 560,
    requirements: [
      { buildingId: 'building.synod.cognition-vault', level: 3 },
      { buildingId: 'building.synod.deep-array', level: 2 },
    ],
    economy: {
      energyConsumption: 31,
      populationUse: 4,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.synod.shield-foundry',
    name: 'Щитовая мануфактура',
    factionId: 'synod',
    zoneId: 'military',
    fieldCost: 3,
    maxLevel: 12,
    assetId: 'building.synod.shield-foundry',
    baseCost: { metal: 1_350, crystal: 1_420, gas: 780 },
    baseBuildSeconds: 670,
    requirements: [
      { buildingId: 'building.synod.lattice-yard', level: 3 },
      { buildingId: 'building.synod.deep-array', level: 3 },
    ],
    economy: {
      energyConsumption: 45,
      populationUse: 5,
      stabilityDemand: 14,
    },
  },
] as const;

export const SYNOD_RESEARCH_CATALOG: readonly ResearchDefinition[] = [
  {
    id: 'technology.synod.distributed-construction',
    name: 'Распределённая сборка',
    factionId: 'synod',
    category: 'infrastructure',
    description: 'Разделяет строительные расчёты между узлами и сокращает время развёртывания.',
    maxLevel: 10,
    baseCost: { metal: 480, crystal: 430, gas: 130 },
    baseSeconds: 220,
    requiredLaboratoryLevel: 1,
    requirements: [],
    effects: [{ type: 'CONSTRUCTION_SPEED', percentPerLevel: 6 }],
    assetId: 'technology.synod.distributed-construction',
  },
  {
    id: 'technology.synod.harmonic-grid',
    name: 'Гармоническая энергосеть',
    factionId: 'synod',
    category: 'energy',
    description: 'Согласует реакторы колонии и повышает полезную отдачу энергетического контура.',
    maxLevel: 10,
    baseCost: { metal: 380, crystal: 590, gas: 170 },
    baseSeconds: 280,
    requiredLaboratoryLevel: 1,
    requirements: [{ technologyId: 'technology.synod.distributed-construction', level: 1 }],
    effects: [{ type: 'ENERGY_OUTPUT', percentPerLevel: 7 }],
    assetId: 'technology.synod.harmonic-grid',
  },
  {
    id: 'technology.synod.deep-sight',
    name: 'Глубинное зрение',
    factionId: 'synod',
    category: 'intelligence',
    description: 'Объединяет разнесённые наблюдения в точную картину дальнего пространства.',
    maxLevel: 10,
    baseCost: { metal: 320, crystal: 700, gas: 230 },
    baseSeconds: 320,
    requiredLaboratoryLevel: 2,
    requirements: [{ technologyId: 'technology.synod.harmonic-grid', level: 1 }],
    effects: [{ type: 'SENSOR_STRENGTH', pointsPerLevel: 2 }],
    assetId: 'technology.synod.deep-sight',
  },
  {
    id: 'technology.synod.vector-folding',
    name: 'Свёртка векторов',
    factionId: 'synod',
    category: 'navigation',
    description: 'Предсказывает оптимальные окна разгона и ускоряет согласованные перелёты.',
    maxLevel: 10,
    baseCost: { metal: 590, crystal: 540, gas: 450 },
    baseSeconds: 440,
    requiredLaboratoryLevel: 2,
    requirements: [{ technologyId: 'technology.synod.deep-sight', level: 1 }],
    effects: [{ type: 'FLEET_SPEED', percentPerLevel: 6 }],
    assetId: 'technology.synod.vector-folding',
  },
  {
    id: 'technology.synod.coherent-shields',
    name: 'Когерентные щиты',
    factionId: 'synod',
    category: 'defense',
    description: 'Связывает защитные поля соседних кораблей в устойчивый общий экран.',
    maxLevel: 10,
    baseCost: { metal: 620, crystal: 620, gas: 290 },
    baseSeconds: 500,
    requiredLaboratoryLevel: 3,
    requirements: [{ technologyId: 'technology.synod.distributed-construction', level: 2 }],
    effects: [{ type: 'ARMOR_STRENGTH', percentPerLevel: 4 }],
    assetId: 'technology.synod.coherent-shields',
  },
  {
    id: 'technology.synod.precision-fire',
    name: 'Прецизионный огонь',
    factionId: 'synod',
    category: 'weapons',
    description: 'Объединяет телеметрию флота и повышает результативность каждого залпа.',
    maxLevel: 10,
    baseCost: { metal: 540, crystal: 700, gas: 380 },
    baseSeconds: 560,
    requiredLaboratoryLevel: 3,
    requirements: [
      { technologyId: 'technology.synod.deep-sight', level: 2 },
      { technologyId: 'technology.synod.harmonic-grid', level: 2 },
    ],
    effects: [{ type: 'WEAPON_STRENGTH', percentPerLevel: 6 }],
    assetId: 'technology.synod.precision-fire',
  },
  {
    id: 'technology.synod.seed-consensus',
    name: 'Консенсус основания',
    factionId: 'synod',
    category: 'infrastructure',
    description: 'Синхронизирует автономные модули новой колонии. Каждый уровень увеличивает предел колоний на одну.',
    maxLevel: 5,
    baseCost: { metal: 2_150, crystal: 2_350, gas: 1_450 },
    baseSeconds: 1_100,
    requiredLaboratoryLevel: 3,
    requirements: [
      { technologyId: 'technology.synod.distributed-construction', level: 2 },
      { technologyId: 'technology.synod.vector-folding', level: 2 },
    ],
    effects: [],
    assetId: 'technology.synod.seed-consensus',
  },
  {
    id: 'technology.synod.relay-logistics',
    name: 'Ретрансляционная логистика',
    factionId: 'synod',
    category: 'navigation',
    description: 'Сводит снабжение и навигацию в единую сеть координации дальних операций.',
    maxLevel: 10,
    baseCost: { metal: 690, crystal: 820, gas: 540 },
    baseSeconds: 610,
    requiredLaboratoryLevel: 3,
    requirements: [
      { technologyId: 'technology.synod.distributed-construction', level: 2 },
      { technologyId: 'technology.synod.vector-folding', level: 1 },
    ],
    effects: [{ type: 'FLEET_SPEED', percentPerLevel: 4 }],
    assetId: 'technology.synod.relay-logistics',
  },
  {
    id: 'technology.synod.predictive-screening',
    name: 'Предиктивное экранирование',
    factionId: 'synod',
    category: 'defense',
    description: 'Перенаправляет щиты до попадания, используя прогноз вражеских огневых решений.',
    maxLevel: 10,
    baseCost: { metal: 690, crystal: 1_140, gas: 660 },
    baseSeconds: 720,
    requiredLaboratoryLevel: 4,
    requirements: [
      { technologyId: 'technology.synod.harmonic-grid', level: 3 },
      { technologyId: 'technology.synod.coherent-shields', level: 2 },
    ],
    effects: [{ type: 'ARMOR_STRENGTH', percentPerLevel: 4 }],
    assetId: 'technology.synod.predictive-screening',
  },
  {
    id: 'technology.synod.chorus-command',
    name: 'Хоровое командование',
    factionId: 'synod',
    category: 'weapons',
    description: 'Сводит сенсоры и огневые решения соединения в один согласованный цикл.',
    maxLevel: 10,
    baseCost: { metal: 920, crystal: 1_420, gas: 850 },
    baseSeconds: 840,
    requiredLaboratoryLevel: 5,
    requirements: [
      { technologyId: 'technology.synod.deep-sight', level: 3 },
      { technologyId: 'technology.synod.precision-fire', level: 3 },
    ],
    effects: [{ type: 'WEAPON_STRENGTH', percentPerLevel: 4 }],
    assetId: 'technology.synod.chorus-command',
  },
] as const;

export const SYNOD_UNIT_CATALOG: readonly UnitDefinition[] = [
  {
    id: 'ship.synod.whisper',
    name: 'Разведчик «Шёпот»',
    factionId: 'synod',
    kind: 'ship',
    role: 'scout',
    description: 'Лёгкий сенсорный корпус, передающий наблюдения в общую сеть.',
    assetId: 'ship.synod.whisper',
    baseCost: { metal: 360, crystal: 570, gas: 190 },
    baseSeconds: 165,
    populationCost: 1,
    hangarCost: 1,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.synod.lattice-yard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.synod.deep-sight', level: 1 }],
    stats: { speed: 16, cargo: 18, attack: 5, armor: 14, shield: 14 },
  },
  {
    id: 'ship.synod.thread-carrier',
    name: 'Транспорт «Нить»',
    factionId: 'synod',
    kind: 'ship',
    role: 'transport',
    description: 'Сетевой транспорт для точного снабжения удалённых колоний.',
    assetId: 'ship.synod.thread-carrier',
    baseCost: { metal: 610, crystal: 420, gas: 250 },
    baseSeconds: 225,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.synod.lattice-yard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.synod.distributed-construction', level: 1 }],
    stats: { speed: 10, cargo: 1_260, attack: 2, armor: 28, shield: 22 },
  },
  {
    id: 'ship.synod.lancet',
    name: 'Истребитель «Ланцет»',
    factionId: 'synod',
    kind: 'ship',
    role: 'fighter',
    description: 'Точный перехватчик, эффективный в согласованной атакующей группе.',
    assetId: 'ship.synod.lancet',
    baseCost: { metal: 500, crystal: 500, gas: 270 },
    baseSeconds: 195,
    populationCost: 1,
    hangarCost: 1,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.synod.lattice-yard', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.synod.precision-fire', level: 1 }],
    stats: { speed: 14, cargo: 25, attack: 38, armor: 17, shield: 17 },
  },
  {
    id: 'ship.synod.ward-frigate',
    name: 'Фрегат «Оберег»',
    factionId: 'synod',
    kind: 'ship',
    role: 'frigate',
    description: 'Щитовой фрегат, удерживающий строй через обмен защитной телеметрией.',
    assetId: 'ship.synod.ward-frigate',
    baseCost: { metal: 1_220, crystal: 1_050, gas: 650 },
    baseSeconds: 390,
    populationCost: 3,
    hangarCost: 3,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.synod.lattice-yard', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.synod.precision-fire', level: 1 },
      { technologyId: 'technology.synod.coherent-shields', level: 1 },
    ],
    stats: { speed: 10, cargo: 110, attack: 88, armor: 82, shield: 66 },
  },
  {
    id: 'ship.synod.seed-ark',
    name: 'Ковчег «Семя»',
    factionId: 'synod',
    kind: 'ship',
    role: 'colonizer',
    description: 'Модульный ковчег, разворачивающий согласованную инфраструктуру новой колонии.',
    assetId: 'ship.synod.seed-ark',
    baseCost: { metal: 4_300, crystal: 4_000, gas: 2_500 },
    baseSeconds: 1_100,
    populationCost: 8,
    hangarCost: 8,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.synod.lattice-yard', level: 3 }],
    researchRequirements: [
      { technologyId: 'technology.synod.vector-folding', level: 2 },
      { technologyId: 'technology.synod.seed-consensus', level: 1 },
    ],
    stats: { speed: 7, cargo: 520, attack: 0, armor: 135, shield: 105 },
  },
  {
    id: 'ship.synod.salvage-mind',
    name: 'Сборщик «Память»',
    factionId: 'synod',
    kind: 'ship',
    role: 'recycler',
    description: 'Автономный сервисный корпус для точного извлечения материалов из обломков.',
    assetId: 'ship.synod.salvage-mind',
    baseCost: { metal: 850, crystal: 720, gas: 560 },
    baseSeconds: 330,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.synod.lattice-yard', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.synod.vector-folding', level: 1 }],
    stats: { speed: 9, cargo: 850, attack: 0, armor: 44, shield: 32 },
  },
  {
    id: 'ship.synod.phase-corvette',
    name: 'Корвет «Фаза»',
    factionId: 'synod',
    kind: 'ship',
    role: 'fighter',
    description: 'Корабль сопровождения, меняющий позицию по прогнозу общей сети.',
    assetId: 'ship.synod.phase-corvette',
    baseCost: { metal: 780, crystal: 820, gas: 450 },
    baseSeconds: 275,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.synod.lattice-yard', level: 2 },
      { buildingId: 'building.synod.precision-forum', level: 1 },
    ],
    researchRequirements: [
      { technologyId: 'technology.synod.precision-fire', level: 2 },
      { technologyId: 'technology.synod.deep-sight', level: 2 },
    ],
    stats: { speed: 14, cargo: 40, attack: 64, armor: 38, shield: 36 },
  },
  {
    id: 'ship.synod.chorus-cruiser',
    name: 'Крейсер «Хор»',
    factionId: 'synod',
    kind: 'ship',
    role: 'frigate',
    description: 'Линейный корабль, усиливающий точность и защиту соединения.',
    assetId: 'ship.synod.chorus-cruiser',
    baseCost: { metal: 2_750, crystal: 2_650, gas: 1_550 },
    baseSeconds: 720,
    populationCost: 6,
    hangarCost: 6,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.synod.lattice-yard', level: 4 },
      { buildingId: 'building.synod.precision-forum', level: 2 },
    ],
    researchRequirements: [
      { technologyId: 'technology.synod.coherent-shields', level: 3 },
      { technologyId: 'technology.synod.precision-fire', level: 3 },
    ],
    stats: { speed: 8, cargo: 210, attack: 190, armor: 190, shield: 150 },
  },
  {
    id: 'ship.synod.relay-carrier',
    name: 'Носитель «Реле»',
    factionId: 'synod',
    kind: 'ship',
    role: 'transport',
    description: 'Дальняя командно-снабженческая платформа для сетевых операций.',
    assetId: 'ship.synod.relay-carrier',
    baseCost: { metal: 3_600, crystal: 3_850, gas: 2_350 },
    baseSeconds: 900,
    populationCost: 8,
    hangarCost: 8,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.synod.lattice-yard', level: 5 },
      { buildingId: 'building.synod.relay-archive', level: 3 },
    ],
    researchRequirements: [
      { technologyId: 'technology.synod.relay-logistics', level: 2 },
      { technologyId: 'technology.synod.chorus-command', level: 2 },
    ],
    stats: { speed: 8, cargo: 2_550, attack: 82, armor: 240, shield: 230 },
  },
  {
    id: 'ship.synod.oracle-dreadnought',
    name: 'Дредноут «Оракул»',
    factionId: 'synod',
    kind: 'ship',
    role: 'frigate',
    description: 'Тяжёлый координационный корпус, выигрывающий бой точностью и щитовыми связями.',
    assetId: 'ship.synod.oracle-dreadnought',
    baseCost: { metal: 7_400, crystal: 7_600, gas: 4_900 },
    baseSeconds: 1_680,
    populationCost: 14,
    hangarCost: 14,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.synod.lattice-yard', level: 6 },
      { buildingId: 'building.synod.precision-forum', level: 4 },
    ],
    researchRequirements: [
      { technologyId: 'technology.synod.precision-fire', level: 5 },
      { technologyId: 'technology.synod.coherent-shields', level: 5 },
      { technologyId: 'technology.synod.predictive-screening', level: 3 },
    ],
    stats: { speed: 6, cargo: 480, attack: 455, armor: 520, shield: 500 },
  },
  {
    id: 'defense.synod.lance-node',
    name: 'Узел направленного импульса',
    factionId: 'synod',
    kind: 'defense',
    role: 'kinetic',
    description: 'Точный защитный излучатель для поражения малых целей.',
    assetId: 'defense.synod.lance-node',
    baseCost: { metal: 360, crystal: 240, gas: 90 },
    baseSeconds: 135,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 1,
    buildingRequirements: [{ buildingId: 'building.synod.deep-array', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.synod.precision-fire', level: 1 }],
    stats: { speed: 0, cargo: 0, attack: 42, armor: 34, shield: 16 },
  },
  {
    id: 'defense.synod.arc-silo',
    name: 'Дуговой пусковой узел',
    factionId: 'synod',
    kind: 'defense',
    role: 'missile',
    description: 'Согласованный залповый комплекс против крупных целей.',
    assetId: 'defense.synod.arc-silo',
    baseCost: { metal: 540, crystal: 420, gas: 230 },
    baseSeconds: 195,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 2,
    buildingRequirements: [{ buildingId: 'building.synod.deep-array', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.synod.precision-fire', level: 2 }],
    stats: { speed: 0, cargo: 0, attack: 90, armor: 30, shield: 18 },
  },
  {
    id: 'defense.synod.harmonic-screen',
    name: 'Гармонический экран',
    factionId: 'synod',
    kind: 'defense',
    role: 'shield',
    description: 'Стационарный узел, объединяющий защитные поля планетарной сети.',
    assetId: 'defense.synod.harmonic-screen',
    baseCost: { metal: 430, crystal: 860, gas: 390 },
    baseSeconds: 270,
    populationCost: 2,
    hangarCost: 0,
    defenseGridCost: 3,
    buildingRequirements: [{ buildingId: 'building.synod.deep-array', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.synod.harmonic-grid', level: 2 },
      { technologyId: 'technology.synod.coherent-shields', level: 1 },
    ],
    stats: { speed: 0, cargo: 0, attack: 0, armor: 26, shield: 190 },
  },
  {
    id: 'defense.synod.predictive-intercept',
    name: 'Предиктивный перехватчик',
    factionId: 'synod',
    kind: 'defense',
    role: 'kinetic',
    description: 'Сеть скоростных узлов, открывающая огонь по прогнозируемой траектории.',
    assetId: 'defense.synod.predictive-intercept',
    baseCost: { metal: 650, crystal: 650, gas: 290 },
    baseSeconds: 215,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 2,
    buildingRequirements: [{ buildingId: 'building.synod.shield-foundry', level: 1 }],
    researchRequirements: [
      { technologyId: 'technology.synod.deep-sight', level: 2 },
      { technologyId: 'technology.synod.precision-fire', level: 2 },
    ],
    stats: { speed: 0, cargo: 0, attack: 78, armor: 48, shield: 34 },
  },
  {
    id: 'defense.synod.concord-bastion',
    name: 'Бастион согласия',
    factionId: 'synod',
    kind: 'defense',
    role: 'shield',
    description: 'Тяжёлый щитовой комплекс, связывающий оборону в единый контур.',
    assetId: 'defense.synod.concord-bastion',
    baseCost: { metal: 1_450, crystal: 1_650, gas: 900 },
    baseSeconds: 500,
    populationCost: 3,
    hangarCost: 0,
    defenseGridCost: 5,
    buildingRequirements: [{ buildingId: 'building.synod.shield-foundry', level: 3 }],
    researchRequirements: [
      { technologyId: 'technology.synod.chorus-command', level: 2 },
      { technologyId: 'technology.synod.predictive-screening', level: 2 },
    ],
    stats: { speed: 0, cargo: 0, attack: 165, armor: 145, shield: 180 },
  },
] as const;
