import type { BuildingDefinition } from '../planet/buildingDefinitions';
import type { ResearchDefinition } from '../research/types';
import type { UnitDefinition } from '../units/types';

export const VEYRA_BUILDING_CATALOG: readonly BuildingDefinition[] = [
  {
    id: 'building.veyra.swarm-heart',
    name: 'Сердце роя',
    factionId: 'veyra',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 10,
    assetId: 'building.veyra.swarm-heart',
    baseCost: { metal: 250, crystal: 250, gas: 65 },
    baseBuildSeconds: 50,
    requirements: [],
    economy: {
      storageCapacity: { metal: 1_800, crystal: 2_200, gas: 1_900 },
      energyConsumption: 6,
      populationCapacity: 36,
    },
  },
  {
    id: 'building.veyra.alloy-bloom',
    name: 'Сплавный цветок',
    factionId: 'veyra',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.veyra.alloy-bloom',
    baseCost: { metal: 170, crystal: 105, gas: 30 },
    baseBuildSeconds: 75,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 1 }],
    economy: {
      resourceProductionPerHour: { metal: 125 },
      energyConsumption: 15,
      populationUse: 1,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.veyra.crystal-grove',
    name: 'Кристальная роща',
    factionId: 'veyra',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.veyra.crystal-grove',
    baseCost: { metal: 155, crystal: 185, gas: 40 },
    baseBuildSeconds: 90,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 1 }],
    economy: {
      resourceProductionPerHour: { crystal: 108 },
      energyConsumption: 18,
      populationUse: 1,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.veyra.vapor-root',
    name: 'Газовый корень',
    factionId: 'veyra',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.veyra.vapor-root',
    baseCost: { metal: 185, crystal: 165, gas: 100 },
    baseBuildSeconds: 115,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 1 }],
    economy: {
      resourceProductionPerHour: { gas: 66 },
      energyConsumption: 21,
      populationUse: 1,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.veyra.solar-membrane',
    name: 'Солнечная мембрана',
    factionId: 'veyra',
    zoneId: 'resource',
    fieldCost: 1,
    maxLevel: 20,
    assetId: 'building.veyra.solar-membrane',
    baseCost: { metal: 220, crystal: 215, gas: 50 },
    baseBuildSeconds: 125,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 1 }],
    economy: {
      energyProduction: 130,
      populationUse: 1,
      stabilityCapacity: 55,
    },
  },
  {
    id: 'building.veyra.memory-pod',
    name: 'Капсула памяти',
    factionId: 'veyra',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 15,
    assetId: 'building.veyra.memory-pod',
    baseCost: { metal: 560, crystal: 725, gas: 300 },
    baseBuildSeconds: 240,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 2 }],
    economy: {
      energyConsumption: 28,
      populationUse: 2,
      stabilityDemand: 6,
    },
  },
  {
    id: 'building.veyra.living-dock',
    name: 'Живая верфь',
    factionId: 'veyra',
    zoneId: 'industry',
    fieldCost: 3,
    maxLevel: 15,
    assetId: 'building.veyra.living-dock',
    baseCost: { metal: 830, crystal: 945, gas: 495 },
    baseBuildSeconds: 395,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 2 }],
    economy: {
      energyConsumption: 42,
      populationUse: 4,
      stabilityDemand: 13,
    },
  },
  {
    id: 'building.veyra.pulse-canopy',
    name: 'Импульсный полог',
    factionId: 'veyra',
    zoneId: 'military',
    fieldCost: 1,
    maxLevel: 15,
    assetId: 'building.veyra.pulse-canopy',
    baseCost: { metal: 385, crystal: 565, gas: 260 },
    baseBuildSeconds: 185,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 1 }],
    economy: {
      energyConsumption: 14,
      populationUse: 2,
      stabilityDemand: 8,
    },
  },
  {
    id: 'building.veyra.spore-vault',
    name: 'Споровое хранилище',
    factionId: 'veyra',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 15,
    assetId: 'building.veyra.spore-vault',
    baseCost: { metal: 700, crystal: 905, gas: 335 },
    baseBuildSeconds: 290,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 3 }],
    economy: {
      storageCapacity: { metal: 3_600, crystal: 4_800, gas: 3_200 },
      energyConsumption: 20,
      populationUse: 2,
      stabilityDemand: 5,
    },
  },
  {
    id: 'building.veyra.nest-cluster',
    name: 'Гнездовой кластер',
    factionId: 'veyra',
    zoneId: 'industry',
    fieldCost: 2,
    maxLevel: 12,
    assetId: 'building.veyra.nest-cluster',
    baseCost: { metal: 630, crystal: 1_030, gas: 380 },
    baseBuildSeconds: 345,
    requirements: [{ buildingId: 'building.veyra.swarm-heart', level: 3 }],
    economy: {
      populationCapacity: 84,
      energyConsumption: 16,
      stabilityCapacity: 86,
    },
  },
  {
    id: 'building.veyra.hunter-node',
    name: 'Узел охотника',
    factionId: 'veyra',
    zoneId: 'military',
    fieldCost: 2,
    maxLevel: 10,
    assetId: 'building.veyra.hunter-node',
    baseCost: { metal: 845, crystal: 1_450, gas: 730 },
    baseBuildSeconds: 495,
    requirements: [
      { buildingId: 'building.veyra.memory-pod', level: 3 },
      { buildingId: 'building.veyra.pulse-canopy', level: 2 },
    ],
    economy: {
      energyConsumption: 31,
      populationUse: 4,
      stabilityDemand: 10,
    },
  },
  {
    id: 'building.veyra.carapace-forge',
    name: 'Кузница панциря',
    factionId: 'veyra',
    zoneId: 'military',
    fieldCost: 3,
    maxLevel: 12,
    assetId: 'building.veyra.carapace-forge',
    baseCost: { metal: 1_215, crystal: 1_490, gas: 875 },
    baseBuildSeconds: 590,
    requirements: [
      { buildingId: 'building.veyra.living-dock', level: 3 },
      { buildingId: 'building.veyra.pulse-canopy', level: 3 },
    ],
    economy: {
      energyConsumption: 45,
      populationUse: 5,
      stabilityDemand: 14,
    },
  },
] as const;

export const VEYRA_RESEARCH_CATALOG: readonly ResearchDefinition[] = [
  {
    id: 'technology.veyra.adaptive-growth',
    name: 'Адаптивный рост',
    factionId: 'veyra',
    category: 'infrastructure',
    description: 'Разделяет строительные расчёты между узлами и сокращает время развёртывания.',
    maxLevel: 10,
    baseCost: { metal: 430, crystal: 450, gas: 145 },
    baseSeconds: 195,
    requiredLaboratoryLevel: 1,
    requirements: [],
    effects: [{ type: 'CONSTRUCTION_SPEED', percentPerLevel: 8 }],
    assetId: 'technology.veyra.adaptive-growth',
  },
  {
    id: 'technology.veyra.photosynthetic-grid',
    name: 'Фотосинтетическая сеть',
    factionId: 'veyra',
    category: 'energy',
    description: 'Согласует реакторы колонии и повышает полезную отдачу энергетического контура.',
    maxLevel: 10,
    baseCost: { metal: 340, crystal: 620, gas: 190 },
    baseSeconds: 245,
    requiredLaboratoryLevel: 1,
    requirements: [{ technologyId: 'technology.veyra.adaptive-growth', level: 1 }],
    effects: [{ type: 'ENERGY_OUTPUT', percentPerLevel: 5 }],
    assetId: 'technology.veyra.photosynthetic-grid',
  },
  {
    id: 'technology.veyra.echo-sense',
    name: 'Эхолокационное чувство',
    factionId: 'veyra',
    category: 'intelligence',
    description: 'Объединяет разнесённые наблюдения в точную картину дальнего пространства.',
    maxLevel: 10,
    baseCost: { metal: 290, crystal: 735, gas: 260 },
    baseSeconds: 280,
    requiredLaboratoryLevel: 2,
    requirements: [{ technologyId: 'technology.veyra.photosynthetic-grid', level: 1 }],
    effects: [{ type: 'SENSOR_STRENGTH', pointsPerLevel: 2 }],
    assetId: 'technology.veyra.echo-sense',
  },
  {
    id: 'technology.veyra.living-thrust',
    name: 'Живой импульс',
    factionId: 'veyra',
    category: 'navigation',
    description: 'Предсказывает оптимальные окна разгона и ускоряет перелёты живых кораблей.',
    maxLevel: 10,
    baseCost: { metal: 530, crystal: 565, gas: 505 },
    baseSeconds: 385,
    requiredLaboratoryLevel: 2,
    requirements: [{ technologyId: 'technology.veyra.echo-sense', level: 1 }],
    effects: [{ type: 'FLEET_SPEED', percentPerLevel: 8 }],
    assetId: 'technology.veyra.living-thrust',
  },
  {
    id: 'technology.veyra.carapace-weave',
    name: 'Переплетение панциря',
    factionId: 'veyra',
    category: 'defense',
    description: 'Связывает защитные поля кораблей одной стаи в устойчивый общий экран.',
    maxLevel: 10,
    baseCost: { metal: 560, crystal: 650, gas: 325 },
    baseSeconds: 440,
    requiredLaboratoryLevel: 3,
    requirements: [{ technologyId: 'technology.veyra.adaptive-growth', level: 2 }],
    effects: [{ type: 'ARMOR_STRENGTH', percentPerLevel: 3 }],
    assetId: 'technology.veyra.carapace-weave',
  },
  {
    id: 'technology.veyra.predator-instinct',
    name: 'Инстинкт хищника',
    factionId: 'veyra',
    category: 'weapons',
    description: 'Объединяет телеметрию флота и повышает результативность каждого залпа.',
    maxLevel: 10,
    baseCost: { metal: 485, crystal: 735, gas: 425 },
    baseSeconds: 495,
    requiredLaboratoryLevel: 3,
    requirements: [
      { technologyId: 'technology.veyra.echo-sense', level: 2 },
      { technologyId: 'technology.veyra.photosynthetic-grid', level: 2 },
    ],
    effects: [{ type: 'WEAPON_STRENGTH', percentPerLevel: 7 }],
    assetId: 'technology.veyra.predator-instinct',
  },
  {
    id: 'technology.veyra.brood-seeding',
    name: 'Рассев выводка',
    factionId: 'veyra',
    category: 'infrastructure',
    description: 'Синхронизирует автономные модули новой колонии. Каждый уровень увеличивает предел колоний на одну.',
    maxLevel: 5,
    baseCost: { metal: 1_935, crystal: 2_470, gas: 1_625 },
    baseSeconds: 970,
    requiredLaboratoryLevel: 3,
    requirements: [
      { technologyId: 'technology.veyra.adaptive-growth', level: 2 },
      { technologyId: 'technology.veyra.living-thrust', level: 2 },
    ],
    effects: [],
    assetId: 'technology.veyra.brood-seeding',
  },
  {
    id: 'technology.veyra.mycelial-logistics',
    name: 'Мицелиальная логистика',
    factionId: 'veyra',
    category: 'navigation',
    description: 'Сводит снабжение и навигацию в единую сеть координации дальних операций.',
    maxLevel: 10,
    baseCost: { metal: 620, crystal: 860, gas: 605 },
    baseSeconds: 535,
    requiredLaboratoryLevel: 3,
    requirements: [
      { technologyId: 'technology.veyra.adaptive-growth', level: 2 },
      { technologyId: 'technology.veyra.living-thrust', level: 1 },
    ],
    effects: [{ type: 'FLEET_SPEED', percentPerLevel: 6 }],
    assetId: 'technology.veyra.mycelial-logistics',
  },
  {
    id: 'technology.veyra.regenerative-shells',
    name: 'Регенеративная оболочка',
    factionId: 'veyra',
    category: 'defense',
    description: 'Перенаправляет щиты до попадания, используя рефлекторную реакцию на вражеский огонь.',
    maxLevel: 10,
    baseCost: { metal: 620, crystal: 1_195, gas: 740 },
    baseSeconds: 635,
    requiredLaboratoryLevel: 4,
    requirements: [
      { technologyId: 'technology.veyra.photosynthetic-grid', level: 3 },
      { technologyId: 'technology.veyra.carapace-weave', level: 2 },
    ],
    effects: [{ type: 'ARMOR_STRENGTH', percentPerLevel: 3 }],
    assetId: 'technology.veyra.regenerative-shells',
  },
  {
    id: 'technology.veyra.swarm-mind',
    name: 'Разум роя',
    factionId: 'veyra',
    category: 'weapons',
    description: 'Сводит сенсоры и огневые решения соединения в один единый инстинктивный цикл.',
    maxLevel: 10,
    baseCost: { metal: 830, crystal: 1_490, gas: 950 },
    baseSeconds: 740,
    requiredLaboratoryLevel: 5,
    requirements: [
      { technologyId: 'technology.veyra.echo-sense', level: 3 },
      { technologyId: 'technology.veyra.predator-instinct', level: 3 },
    ],
    effects: [{ type: 'WEAPON_STRENGTH', percentPerLevel: 5 }],
    assetId: 'technology.veyra.swarm-mind',
  },
] as const;

export const VEYRA_UNIT_CATALOG: readonly UnitDefinition[] = [
  {
    id: 'ship.veyra.wisp',
    name: 'Разведчик «Огонёк»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'scout',
    description: 'Лёгкий сенсорный корпус, передающий наблюдения в роевой разум.',
    assetId: 'ship.veyra.wisp',
    baseCost: { metal: 325, crystal: 600, gas: 215 },
    baseSeconds: 145,
    populationCost: 1,
    hangarCost: 1,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.veyra.living-dock', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.veyra.echo-sense', level: 1 }],
    stats: { speed: 18, cargo: 21, attack: 5, armor: 11, shield: 13 },
  },
  {
    id: 'ship.veyra.tendril',
    name: 'Транспорт «Усик»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'transport',
    description: 'Сетевой транспорт для точного снабжения удалённых колоний.',
    assetId: 'ship.veyra.tendril',
    baseCost: { metal: 550, crystal: 440, gas: 280 },
    baseSeconds: 200,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.veyra.living-dock', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.veyra.adaptive-growth', level: 1 }],
    stats: { speed: 12, cargo: 1_449, attack: 2, armor: 23, shield: 20 },
  },
  {
    id: 'ship.veyra.sting',
    name: 'Истребитель «Жало»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'fighter',
    description: 'Точный перехватчик, эффективный в быстрой охотничьей стае.',
    assetId: 'ship.veyra.sting',
    baseCost: { metal: 450, crystal: 525, gas: 300 },
    baseSeconds: 170,
    populationCost: 1,
    hangarCost: 1,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.veyra.living-dock', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.veyra.predator-instinct', level: 1 }],
    stats: { speed: 16, cargo: 29, attack: 41, armor: 14, shield: 15 },
  },
  {
    id: 'ship.veyra.shellwing',
    name: 'Фрегат «Панцирокрыл»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'frigate',
    description: 'Щитовой фрегат, удерживающий строй через обмен регенеративными импульсами.',
    assetId: 'ship.veyra.shellwing',
    baseCost: { metal: 1_100, crystal: 1_100, gas: 730 },
    baseSeconds: 345,
    populationCost: 3,
    hangarCost: 3,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.veyra.living-dock', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.veyra.predator-instinct', level: 1 },
      { technologyId: 'technology.veyra.carapace-weave', level: 1 },
    ],
    stats: { speed: 12, cargo: 126, attack: 95, armor: 67, shield: 59 },
  },
  {
    id: 'ship.veyra.brood-ark',
    name: 'Ковчег «Выводок»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'colonizer',
    description: 'Модульный ковчег, разворачивающий саморастущую инфраструктуру новой колонии.',
    assetId: 'ship.veyra.brood-ark',
    baseCost: { metal: 3_870, crystal: 4_200, gas: 2_800 },
    baseSeconds: 970,
    populationCost: 8,
    hangarCost: 8,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.veyra.living-dock', level: 3 }],
    researchRequirements: [
      { technologyId: 'technology.veyra.living-thrust', level: 2 },
      { technologyId: 'technology.veyra.brood-seeding', level: 1 },
    ],
    stats: { speed: 9, cargo: 598, attack: 1, armor: 111, shield: 94 },
  },
  {
    id: 'ship.veyra.devourer',
    name: 'Сборщик «Поглотитель»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'recycler',
    description: 'Автономный сервисный корпус для точного извлечения материалов из обломков.',
    assetId: 'ship.veyra.devourer',
    baseCost: { metal: 765, crystal: 755, gas: 625 },
    baseSeconds: 290,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [{ buildingId: 'building.veyra.living-dock', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.veyra.living-thrust', level: 1 }],
    stats: { speed: 11, cargo: 977, attack: 1, armor: 36, shield: 29 },
  },
  {
    id: 'ship.veyra.dart',
    name: 'Корвет «Стрекоза»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'fighter',
    description: 'Корабль сопровождения, меняющий позицию по прогнозу общей сети.',
    assetId: 'ship.veyra.dart',
    baseCost: { metal: 700, crystal: 860, gas: 505 },
    baseSeconds: 240,
    populationCost: 2,
    hangarCost: 2,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.veyra.living-dock', level: 2 },
      { buildingId: 'building.veyra.hunter-node', level: 1 },
    ],
    researchRequirements: [
      { technologyId: 'technology.veyra.predator-instinct', level: 2 },
      { technologyId: 'technology.veyra.echo-sense', level: 2 },
    ],
    stats: { speed: 16, cargo: 46, attack: 69, armor: 31, shield: 32 },
  },
  {
    id: 'ship.veyra.manta',
    name: 'Крейсер «Манта»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'frigate',
    description: 'Линейный корабль, усиливающий точность и защиту соединения.',
    assetId: 'ship.veyra.manta',
    baseCost: { metal: 2_475, crystal: 2_780, gas: 1_735 },
    baseSeconds: 635,
    populationCost: 6,
    hangarCost: 6,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.veyra.living-dock', level: 4 },
      { buildingId: 'building.veyra.hunter-node', level: 2 },
    ],
    researchRequirements: [
      { technologyId: 'technology.veyra.carapace-weave', level: 3 },
      { technologyId: 'technology.veyra.predator-instinct', level: 3 },
    ],
    stats: { speed: 10, cargo: 241, attack: 205, armor: 156, shield: 135 },
  },
  {
    id: 'ship.veyra.hive-carrier',
    name: 'Носитель «Улей»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'transport',
    description: 'Дальняя командно-снабженческая платформа для роевых операций.',
    assetId: 'ship.veyra.hive-carrier',
    baseCost: { metal: 3_240, crystal: 4_040, gas: 2_630 },
    baseSeconds: 790,
    populationCost: 8,
    hangarCost: 8,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.veyra.living-dock', level: 5 },
      { buildingId: 'building.veyra.spore-vault', level: 3 },
    ],
    researchRequirements: [
      { technologyId: 'technology.veyra.mycelial-logistics', level: 2 },
      { technologyId: 'technology.veyra.swarm-mind', level: 2 },
    ],
    stats: { speed: 10, cargo: 2_932, attack: 89, armor: 197, shield: 207 },
  },
  {
    id: 'ship.veyra.leviathan',
    name: 'Дредноут «Левиафан»',
    factionId: 'veyra',
    kind: 'ship',
    role: 'frigate',
    description: 'Тяжёлый координационный корпус, выигрывающий бой точностью и щитовыми связями.',
    assetId: 'ship.veyra.leviathan',
    baseCost: { metal: 6_660, crystal: 7_980, gas: 5_490 },
    baseSeconds: 1_480,
    populationCost: 14,
    hangarCost: 14,
    defenseGridCost: 0,
    buildingRequirements: [
      { buildingId: 'building.veyra.living-dock', level: 6 },
      { buildingId: 'building.veyra.hunter-node', level: 4 },
    ],
    researchRequirements: [
      { technologyId: 'technology.veyra.predator-instinct', level: 5 },
      { technologyId: 'technology.veyra.carapace-weave', level: 5 },
      { technologyId: 'technology.veyra.regenerative-shells', level: 3 },
    ],
    stats: { speed: 8, cargo: 552, attack: 491, armor: 426, shield: 450 },
  },
  {
    id: 'defense.veyra.thorn-spire',
    name: 'Шиповая башня',
    factionId: 'veyra',
    kind: 'defense',
    role: 'kinetic',
    description: 'Точный защитный излучатель для поражения малых целей.',
    assetId: 'defense.veyra.thorn-spire',
    baseCost: { metal: 325, crystal: 250, gas: 100 },
    baseSeconds: 120,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 1,
    buildingRequirements: [{ buildingId: 'building.veyra.pulse-canopy', level: 1 }],
    researchRequirements: [{ technologyId: 'technology.veyra.predator-instinct', level: 1 }],
    stats: { speed: 0, cargo: 1, attack: 45, armor: 28, shield: 14 },
  },
  {
    id: 'defense.veyra.spore-mortar',
    name: 'Споровый миномёт',
    factionId: 'veyra',
    kind: 'defense',
    role: 'missile',
    description: 'Согласованный залповый комплекс против крупных целей.',
    assetId: 'defense.veyra.spore-mortar',
    baseCost: { metal: 485, crystal: 440, gas: 260 },
    baseSeconds: 170,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 2,
    buildingRequirements: [{ buildingId: 'building.veyra.pulse-canopy', level: 2 }],
    researchRequirements: [{ technologyId: 'technology.veyra.predator-instinct', level: 2 }],
    stats: { speed: 0, cargo: 1, attack: 97, armor: 25, shield: 16 },
  },
  {
    id: 'defense.veyra.living-veil',
    name: 'Живая завеса',
    factionId: 'veyra',
    kind: 'defense',
    role: 'shield',
    description: 'Стационарный узел, объединяющий защитные поля планетарной сети.',
    assetId: 'defense.veyra.living-veil',
    baseCost: { metal: 385, crystal: 905, gas: 435 },
    baseSeconds: 240,
    populationCost: 2,
    hangarCost: 0,
    defenseGridCost: 3,
    buildingRequirements: [{ buildingId: 'building.veyra.pulse-canopy', level: 2 }],
    researchRequirements: [
      { technologyId: 'technology.veyra.photosynthetic-grid', level: 2 },
      { technologyId: 'technology.veyra.carapace-weave', level: 1 },
    ],
    stats: { speed: 0, cargo: 1, attack: 1, armor: 21, shield: 171 },
  },
  {
    id: 'defense.veyra.snapper-node',
    name: 'Хватающий узел',
    factionId: 'veyra',
    kind: 'defense',
    role: 'kinetic',
    description: 'Сеть скоростных узлов, открывающая огонь по прогнозируемой траектории.',
    assetId: 'defense.veyra.snapper-node',
    baseCost: { metal: 585, crystal: 680, gas: 325 },
    baseSeconds: 190,
    populationCost: 1,
    hangarCost: 0,
    defenseGridCost: 2,
    buildingRequirements: [{ buildingId: 'building.veyra.carapace-forge', level: 1 }],
    researchRequirements: [
      { technologyId: 'technology.veyra.echo-sense', level: 2 },
      { technologyId: 'technology.veyra.predator-instinct', level: 2 },
    ],
    stats: { speed: 0, cargo: 1, attack: 84, armor: 39, shield: 31 },
  },
  {
    id: 'defense.veyra.hive-bastion',
    name: 'Бастион улья',
    factionId: 'veyra',
    kind: 'defense',
    role: 'shield',
    description: 'Тяжёлый щитовой комплекс, связывающий оборону в единый контур.',
    assetId: 'defense.veyra.hive-bastion',
    baseCost: { metal: 1_305, crystal: 1_730, gas: 1_010 },
    baseSeconds: 440,
    populationCost: 3,
    hangarCost: 0,
    defenseGridCost: 5,
    buildingRequirements: [{ buildingId: 'building.veyra.carapace-forge', level: 3 }],
    researchRequirements: [
      { technologyId: 'technology.veyra.swarm-mind', level: 2 },
      { technologyId: 'technology.veyra.regenerative-shells', level: 2 },
    ],
    stats: { speed: 0, cargo: 1, attack: 178, armor: 119, shield: 162 },
  },
] as const;
